#!/bin/zsh

for name in Apple Banana Cheery; do 
echo "I like eating $name"
done

for i in {1..5}; do
echo "this is loop number $i"
done

count=1

while [[ $count -le 6 ]]; do
echo "count is $count"
count=$(($count + 1))
done