#!/bin/zsh

# # 1. Use Command Substitution to get data
# CURRENT_USER=$(whoami)
# UPTIME_INFO=$(uptime -p)

# # 2. Use an Argument for the filename
# LOG_FILE=$1

# # 3. Logic: Check if the user provided an argument
# if [[ -z $LOG_FILE ]]; then
#     echo "Error: Please provide a filename. Example: ./logger.zsh log.txt"
#     exit 1
# fi

# # 4. Save the info to the file
# echo "--- Report for $CURRENT_USER ---" > $LOG_FILE
# echo "System Status: $UPTIME_INFO" >> $LOG_FILE
# echo "Report saved to $LOG_FILE"

CURRENT_USER=$(whoami)

LOG_FILE=$1

if [[ -z $LOG_FILE ]]; then
echo "Error: Please provide a filename. Example: ./logger.zsh log.txt"
exit 1
fi

echo "---Report for the $CURRENT_USER---" > $LOG_FILE
echo "fruit name $2" >> $LOG_FILE